---
# tasks file for roles/configure-nginx
- name: add nginx to firewall
  firewalld:
    service: http
    immediate: true
    permanent: true
    state: enabled
- name: Set nginx httpd_can_network_connect flag
  seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

